import "./globals.css";
import { ibmPlexSans } from "@/utils/fonts/fonts-google";

export const metadata = {
  title: "Multi Step Form || Rafael Thumzz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ibmPlexSans.className}>{children}</body>
    </html>
  );
}
